### ISSUE TITLE
Leaks Venafi Credentials.

### ISSUE THREAD

**Issue by SailingYYC** [Venafi/cert-manager-venafi-demo#2]
The logs produced by Venafi's `cert-manager-controller` with he Venafi WebSDK extensions leaks the SDK user credentials in its logs.

```console
issue.go:53] Client is {%!s(*client.Config=&{ false  https://tpp.venafi.example/vedsdk USERNAME PASSWORD   ZONE 0 0 0 
```

**Comment by SailingYYC** [comment]
@arykalin and word on this?

**Comment by arykalin** [comment]
Hi @SailingYYC , I'm sorry, I missed notification email. Thank you for reporting this. I forgot to remove this debug message. On monday I'll publish new cert-manager docker image without this message.

**Comment by SailingYYC** [comment]
Perfect thank you. Based on my digging I suspect this is forked from `v0.4.1` of `cert-manager`?

I'll also let our Enterprise Security team let Venafi support know this is getting resolved as I'd pushed through that channel as well.

Is it possible to tag these with the same tag as the `cert-manager` it is based off of? Ideally ported for every release tag until inclusion.

Thanks again,
Colin

**Comment by arykalin** [comment]
This image yes, new image will be from cert-manager 5.0. Yes, I'll think about tagging, I think it's possible.

**Comment by SailingYYC** [comment]
@arykalin How goes the update? Any ETA? Most appreciated, Colin

**Comment by arykalin** [comment]
Hi @SailingYYC I'm sorry, I still need some more time to finish new image. I hope it will be available tomorrow

**Comment by arykalin** [comment]
Hi @SailingYYC sorry for delay. Please try to update now by running "make install". I updated image to the 0.1.124 versions without a leak.

**Comment by SailingYYC** [comment]
Excellent @arykalin, I'll be testing it shortly. Is this based on v0.5.0?

**Comment by SailingYYC** [comment]
The logging is much more concise. I know there was a `verbose` flag configurable on the `issuers`, would this re-enable that level of debugging?

**Comment by arykalin** [comment]
1. No unfortunately it is still on 0.4.1. I still testing 0.5.0.
2. Verbose flag is a vcert option (library for connecting to Venafi Platform). It wouldn't change much for now.

**Comment by arykalin** [comment]
If you like you can build from repo https://github.com/Venafi/cert-manager It is already on 5.0 version.

**Comment by SailingYYC** [comment]
Perfect, that's what I had suspected. The reason I asked about mirroring the tagging (or maybe use semver `v0.4.1-0.1.124` is to ensure we pair it with the correct Helm chart version, and because we internally have to build a new image with out corporate root certificates installed so it is highly preferable to keep visibility and parity between these 3 linked artifacts.

Thanks again,
Colin

**Comment by arykalin** [comment]
Yes. when I'll finish the testing of our 0.5.0 issuer it will be tagged something like this: 0.5.0.125
