### ISSUE TITLE
JKS support using venafi cert-manager

### ISSUE THREAD

**Issue by sysmatrix1** [Venafi/cert-manager-venafi-demo#6]
Hi,
I am not sure how to use this demo to create JKS using cert-manager. In README, some wrapper scripts are mentioned to create JKS but I am not sure where that script is. Basically, I need to automate the creation of JKS from a venafi certificate using golang.
Any help will be appreaciated!

**Comment by arykalin** [comment]
Hi @sysmatrix1 , could you clarify your use case. You need to get certificate from Venafi Platform and put it into Java Key Store? Do you need to do it inside kubernetes cluster?

**Comment by sysmatrix1** [comment]
@arykalin Thanks so much for responding to my request. Yes that's exactly what I need, I need it as a secret in Kubernetes cluster. I understand I can use openssl or keytool to convert the certificate into jks format but want to know if it's all possible in a kubernetes operator.

**Comment by wgoulet** [comment]
Hi @sysmatrix1 the section of the readme was truncated where I had described this use case; apologies. However what I had done for that example is pretty much exactly what you have described; I had added a script to the docker startup sequence that would pull the certificate & private key from Kubernetes secrets, convert them to a jks file with keytool, then copy the resulting jks file to the correct location required by the app. I am not aware of a way to create the jks files natively in Kubernetes secrets.

Here's an example startup.sh script that does this (note that this solution assumes the the certificate data & passphrase have been mounted in the container and are accessible at /etc/certdata):
```
#!/bin/sh
keytool -importkeystore -deststorepass `cat /etc/certdata/p12pass` -destkeystore /etc/sbkeystore.jks -srckeystore /etc/certdata/p12encoded -srcstoretype PKCS12 -srcstorepass `cat /etc/certdata/p12pass`

java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
```

**Comment by sysmatrix1** [comment]
@wgoulet Thanks! It would be great if VCert has the ability to download certificate as JKS. Venafi TPP web UI does let me download the certificate as JKS. Similar functionality in VCert will be a good feature.

**Comment by tr1ck3r** [comment]
Hi @sysmatrix1 can you please share a bit more information about the application(s) you have that consume JKS keystores?  We honestly haven't seen any JKS usage to date in the Kubernetes ecosystem so I'm curious if this was something you or your organization developed yourselves or is a generally available solution you obtained from a third party.  You probably have seen where Oracle is moving away from JKS, transitioning to PKCS#12 as their default keystore in JDK 9 and the PKCS#12 format is supported by VCert.

Venafi doesn't have any near term plans to enhance VCert to support JKS so my recommendation is to follow the example provided by @wgoulet or to call the Venafi Platform's POST Certificates/Retrieve REST API method directly for this use case.

**Comment by sysmatrix1** [comment]
Thanks @tr1ck3r. We have a few legacy java applications which need to run in kubernetes environment. These applications need jks support. I will try to use github.com/pavel-v-chernykh/keystore-go. If that doesn't work, I can use the solution suggested by @wgoulet. Thank you so much for responding to my request.
